[project]
name = "lspyc"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
authors = [
    { email = "zhanpengliu@tencent.com" }
]
requires-python = ">=3.12"
dependencies = [
    "websockets>=16.0",
]

[build-system]
requires = ["uv_build>=0.8.0,<0.9"]
build-backend = "uv_build"
